/** Toàn bộ chuỗi UI tiếng Việt — sửa tại đây, không dùng thư viện i18n */

export const strings = {
  appName: 'My X Flows',
  appTagline: 'Workflow node-based trên Google Flow & Gemini',

  // Side panel tabs
  tabWorkflow: 'Workflow',
  subTemplates: 'Templates',
  subWorkflows: 'Workflows',

  // Workspace
  workspaceCurrent: 'hiện tại',
  workspaceNew: 'Workspace mới',
  workspaceRename: 'Đổi tên workspace',
  workspaceDelete: 'Xoá workspace',
  workspaceCreate: 'Tạo workspace',
  workspaceDeleteConfirm: (name: string) => `Xoá workspace "${name}"?`,
  workspaceDeleteWithWorkflows: (n: number) =>
    `Workspace còn ${n} workflow. Xoá luôn các workflow này (chuyển vào thùng rác)?`,
  workspaceDeleteLast: 'Không thể xoá workspace cuối cùng',
  workspaceDeleted: 'Đã xoá workspace',
  workspaceEmpty: 'Chưa có workspace',

  // Workflow list
  searchPlaceholder: 'Tìm workflow...',
  filterAll: 'Tất cả',
  filterEnabled: 'Đang bật',
  filterDisabled: 'Đã tắt',
  filterError: 'Lỗi gần nhất',
  runAll: 'Chạy tất cả',
  runAllConfirm: (n: number) => `Chạy ${n} workflow đang bật trong workspace hiện tại?`,
  addNew: 'Thêm',
  addBlank: 'Workflow trống',
  addFromTemplate: 'Từ template',
  addImport: 'Import file',
  refresh: 'Làm mới',
  import: 'Import',
  export: 'Export',
  nodesCount: (n: number) => `${n} nodes`,
  emptyWorkflows: 'Chưa có workflow nào. Bấm + Thêm để tạo.',
  emptyTemplates: 'Chưa có template.',
  useTemplate: 'Dùng mẫu',
  rename: 'Đổi tên',
  duplicate: 'Nhân bản',
  moveWorkspace: 'Chuyển workspace',
  saveAsTemplate: 'Lưu thành template',
  delete: 'Xoá',
  openEditor: 'Mở editor',
  undoDelete: 'Hoàn tác xoá',
  softDeleted: 'Đã chuyển vào thùng rác',
  copySuffix: '(copy)',
  importSuffix: '(nhập)',

  // Editor
  save: 'Lưu',
  saved: 'Đã lưu',
  dirty: 'Chưa lưu',
  reset: 'Reset',
  resetConfirm: 'Xoá kết quả chạy đang hiển thị trên các node? Cấu hình vẫn giữ nguyên.',
  lock: 'Khoá canvas',
  unlock: 'Mở khoá',
  close: 'Đóng',
  closeDirtyTitle: 'Có thay đổi chưa lưu',
  closeDirtySave: 'Lưu',
  closeDirtyDiscard: 'Bỏ thay đổi',
  closeDirtyCancel: 'Huỷ',
  restoreDraftTitle: 'Phát hiện bản nháp',
  restoreDraftBody: 'Có bản nháp mới hơn bản đã lưu. Khôi phục?',
  restoreDraftYes: 'Khôi phục bản nháp',
  restoreDraftNo: 'Dùng bản đã lưu',
  fitView: 'Căn giữa',
  maxSpeed: 'Max Speed',
  run: 'Chạy',
  runNode: 'Chạy node',
  runFromHere: 'Chạy từ đây',
  stop: 'Dừng',
  stopRun: 'Dừng chạy',
  cancel: 'Huỷ',
  undo: 'Hoàn tác',
  redo: 'Làm lại',
  autoLayout: 'Tự sắp xếp',
  settings: 'Cài đặt',
  notifications: 'Thông báo',
  selectTool: 'Chọn',
  panTool: 'Pan',
  addNode: 'Thêm node',
  addNote: 'Ghi chú',
  addMedia: 'Thêm ảnh/video',
  zoomIn: 'Phóng to',
  zoomOut: 'Thu nhỏ',
  resetView: 'Đặt lại view',
  docs: 'Tài liệu',

  // Node picker
  nodePickerTitle: 'Chọn node',
  nodePickerSearch: 'Tìm node...',
  nodePickerHint: '↑↓ Di chuyển · Enter Chọn · Esc Đóng',
  catInput: 'Input',
  catLlm: 'LLM',
  catGenerate: 'Generate',
  catOutput: 'Output',
  catAnnotation: 'Annotation',

  // Nodes
  nodeAsset: 'Asset',
  nodeAssetDesc: 'Asset có sẵn trên Google Flow (hoặc file local) kèm label để dùng trong prompt',
  nodeText: 'Text',
  nodeTextDesc: 'Đã gộp vào Prompt',
  nodePrompt: 'Prompt',
  nodePromptDesc: 'Nối prompt phía trước; thay [Label] bằng địa chỉ asset trên Flow; nhận Generate Video làm cảnh trước',
  nodeGenerateImage: 'Generate Image',
  nodeGenerateImageDesc: 'Tạo ảnh (tỉ lệ, số lượng, độ phân giải, model)',
  nodeGenerateVideo: 'Generate Video',
  nodeGenerateVideoDesc: 'Tạo video (tỉ lệ, độ dài, độ phân giải, model)',
  nodeAutoDownload: 'Auto Download',
  nodeAutoDownloadDesc: 'Tự tải kết quả của node trước',
  nodeNote: 'Note',
  nodeNoteDesc: 'Ghi chú trên canvas, không thực thi',
  assetLabel: 'Label',
  missingFile: 'Thiếu file',
  pickFileAgain: 'Chọn lại',
  dropOrPick: 'Kéo thả hoặc chọn file',
  dropOrPickImage: 'Kéo thả hoặc chọn ảnh',
  dropOrPickVideo: 'Kéo thả hoặc chọn video',
  dropOrPickAudio: 'Kéo thả hoặc chọn audio',
  pickFromFlow: 'Từ Google Flow',
  pickFlowAssetHint: 'Chọn asset có sẵn trên Google Flow',
  pickFromLocal: 'Chọn file',
  flowPickerTitle: 'Chọn asset từ Google Flow',
  flowPickerHint:
    'Mở project trên tab Google Flow (flow.google.com), rồi bấm Làm mới để quét media.',
  flowPickerEmpty: 'Không thấy media nào. Hãy mở project có ảnh/video trên Flow rồi thử lại.',
  flowPickerLoading: 'Đang quét Google Flow…',
  flowPickerFetching: 'Đang tải asset…',
  flowPickerRefresh: 'Làm mới',
  flowPickerSelect: 'Dùng asset này',
  flowPickerNoMediaId: 'không có media id',
  flowPickerAuth: 'Chưa đăng nhập Google Flow. Đăng nhập trên tab Flow rồi thử lại.',
  flowPickerLogin: 'Đăng nhập Google Flow',
  flowPickerLoginHint: 'Đã mở tab Flow — đăng nhập xong quay lại bấm Làm mới.',
  flowPickerOpeningLogin: 'Đang mở Google Flow…',
  flowPickerConnError:
    'Không kết nối được tab Google Flow. Hãy mở https://flow.google.com , reload trang, rồi bấm Làm mới.',
  replaceAsset: 'Đổi asset',
  preview: 'Preview',
  aspectRatio: 'Tỉ lệ khung hình',
  outputCount: 'Số lượng tạo ra',
  resolution: 'Độ phân giải',
  durationSec: 'Độ dài video (giây)',
  model: 'Model',
  inspectorTitle: 'Inspector',
  providerFlow: 'Google Flow',
  providerGemini: 'Gemini',

  // Status
  statusQueued: 'Đang chờ',
  statusRunning: 'Đang chạy',
  statusUploading: 'Đang tải lên',
  statusGenerating: 'Đang tạo',
  statusSuccess: 'Xong',
  statusError: 'Lỗi',
  statusSkipped: 'Bỏ qua',
  statusCancelled: 'Đã huỷ',
  authRequired: 'Chưa đăng nhập provider',
  quotaExceeded: 'Hết hạn mức',
  contentPolicy: 'Vi phạm chính sách nội dung',
  timeout: 'Hết thời gian chờ',
  selectorNotFound: 'Không tìm thấy phần tử UI',
  uploadFailed: 'Tải file thất bại',
  tabLost: 'Tab provider bị đóng',
  unknownError: 'Lỗi không xác định',

  // Export / Import
  exportTitle: 'Export workflow',
  exportFormat: 'Định dạng',
  exportFormatZip: '.xflow.zip (mặc định)',
  exportFormatJson: '.xflow.json',
  exportIncludeAssets: 'Kèm file media',
  exportIncludeOutputs: 'Kèm kết quả chạy gần nhất',
  exportSummary: (w: number, n: number, a: number, size: string) =>
    `${w} workflow · ${n} nodes · ${a} asset · ~${size}`,
  importTitle: 'Import workflow',
  importPreview: 'Xem trước import',
  importTargetWorkspace: 'Workspace đích',
  importCreateWorkspace: 'Tạo workspace mới từ file',
  importDupCopy: 'Tạo bản sao',
  importDupOverwrite: 'Ghi đè',
  importDupSkip: 'Bỏ qua',
  importCommit: 'Nhập',
  importDropZone: 'Thả file .xflow.zip / .xflow.json vào đây',
  importDropCanvas: 'Mở thành workflow mới hoặc chèn node vào workflow hiện tại?',
  importOpenNew: 'Mở thành workflow mới',
  importInsert: 'Chèn node vào workflow hiện tại',
  importTooNew: 'File được tạo từ phiên bản mới hơn, hãy cập nhật extension',
  importInvalid: 'File không hợp lệ',
  importSuccess: (n: number) => `Đã nhập ${n} workflow`,
  backup: 'Backup',
  restore: 'Restore',
  backupDone: 'Đã tạo bản backup',
  restoreDone: 'Đã khôi phục dữ liệu',
  restoreConfirm: 'Restore sẽ ghi đè dữ liệu hiện tại. Tiếp tục?',

  // Settings
  settingsTitle: 'Cài đặt',
  settingsDownloadFolder: 'Thư mục tải mặc định',
  settingsImportMaxZip: 'Giới hạn zip import (MB)',
  settingsImportMaxJson: 'Giới hạn json import (MB)',
  settingsDefaultConcurrency: 'Concurrency mặc định',
  settingsDefaultGeminiModel: 'Model Gemini mặc định',
  settingsRemoteConfig: 'Remote selector config URL',
  settingsVersion: 'Phiên bản',
  settingsCheckUpdate: 'Kiểm tra cập nhật',
  settingsStorageEstimate: 'Dung lượng đã dùng',
  settingsCleanup: 'Dọn asset/output mồ côi',
  settingsProviderStatus: 'Tình trạng provider',
  settingsDiagnose: 'Chẩn đoán selector',
  providerOk: 'Đã đăng nhập',
  providerUnauth: 'Chưa đăng nhập',
  providerError: 'Driver lỗi',

  // Queue footer
  queueRunning: (n: number) => `Đang chạy ${n}`,
  queueWaiting: (n: number) => `Chờ ${n}`,
  queueIdle: 'Hàng đợi trống',

  // Common
  confirm: 'Xác nhận',
  ok: 'OK',
  yes: 'Có',
  no: 'Không',
  loading: 'Đang tải…',
  error: 'Lỗi',
  success: 'Thành công',
  justNow: 'vừa xong',
} as const;

export type Strings = typeof strings;
