/** Toàn bộ chuỗi UI tiếng Việt — sửa tại đây, không dùng thư viện i18n */

export const strings = {
  appName: 'My X Flows',
  appTagline: 'Workflow node-based trên Google Flow & Gemini',

  // Side panel tabs
  tabWorkflow: 'Workflow',
  subTemplates: 'Templates',
  subWorkflows: 'Workflows',

  // Workspace
  workspaceCurrent: 'hiện tại',
  workspaceNew: 'Workspace mới',
  workspaceRename: 'Đổi tên workspace',
  workspaceDelete: 'Xoá workspace',
  workspaceCreate: 'Tạo workspace',
  workspaceDeleteConfirm: (name: string) => `Xoá workspace "${name}"?`,
  workspaceDeleteWithWorkflows: (n: number) =>
    `Workspace còn ${n} workflow. Xoá luôn các workflow này (chuyển vào thùng rác)?`,
  workspaceDeleteLast: 'Không thể xoá workspace cuối cùng',
  workspaceDeleted: 'Đã xoá workspace',
  workspaceEmpty: 'Chưa có workspace',

  // Workflow list
  searchPlaceholder: 'Tìm workflow...',
  filterAll: 'Tất cả',
  filterEnabled: 'Đang bật',
  filterDisabled: 'Đã tắt',
  filterError: 'Lỗi gần nhất',
  runAll: 'Chạy tất cả',
  runAllConfirm: (n: number) => `Chạy ${n} workflow đang bật trong workspace hiện tại?`,
  addNew: 'Thêm',
  addBlank: 'Workflow trống',
  addFromTemplate: 'Từ template',
  addImport: 'Import file',
  refresh: 'Làm mới',
  import: 'Import',
  export: 'Export',
  nodesCount: (n: number) => `${n} nodes`,
  emptyWorkflows: 'Chưa có workflow nào. Bấm + Thêm để tạo.',
  emptyTemplates: 'Chưa có template.',
  useTemplate: 'Dùng mẫu',
  rename: 'Đổi tên',
  duplicate: 'Nhân bản',
  moveWorkspace: 'Chuyển workspace',
  saveAsTemplate: 'Lưu thành template',
  delete: 'Xoá',
  openEditor: 'Mở editor',
  undoDelete: 'Hoàn tác xoá',
  softDeleted: 'Đã chuyển vào thùng rác',
  workflowDeleted: 'Workflow đã bị xoá',
  nodeNotFound: 'Không tìm thấy node',
  regenerateNotGenerateNode: 'Chỉ tạo lại được node tạo ảnh hoặc tạo video',
  regenerateNodeDisabled: 'Node đang tắt, không tạo lại được',
  mergeWaitingClips: 'Đang chờ đủ clip để ghép',
  copySuffix: '(copy)',
  importSuffix: '(nhập)',

  // Editor
  save: 'Lưu',
  saved: 'Đã lưu',
  dirty: 'Chưa lưu',
  reset: 'Reset',
  resetConfirm: 'Xoá kết quả chạy đang hiển thị trên các node? Cấu hình vẫn giữ nguyên.',
  lock: 'Khoá canvas',
  unlock: 'Mở khoá',
  close: 'Đóng',
  closeDirtyTitle: 'Có thay đổi chưa lưu',
  closeDirtySave: 'Lưu',
  closeDirtyDiscard: 'Bỏ thay đổi',
  closeDirtyCancel: 'Huỷ',
  restoreDraftTitle: 'Phát hiện bản nháp',
  restoreDraftBody: 'Có bản nháp mới hơn bản đã lưu. Khôi phục?',
  restoreDraftYes: 'Khôi phục bản nháp',
  restoreDraftNo: 'Dùng bản đã lưu',
  fitView: 'Căn giữa',
  maxSpeed: 'Max Speed',
  run: 'Chạy',
  runNode: 'Chạy node',
  runFromHere: 'Chạy từ đây',
  stop: 'Dừng',
  stopRun: 'Dừng chạy',
  cancel: 'Huỷ',
  undo: 'Hoàn tác',
  redo: 'Làm lại',
  autoLayout: 'Tự sắp xếp',
  settings: 'Cài đặt',
  notifications: 'Thông báo',
  selectTool: 'Chọn',
  panTool: 'Pan',
  addNode: 'Thêm node',
  addNote: 'Ghi chú',
  addMedia: 'Thêm ảnh/video',
  zoomIn: 'Phóng to',
  zoomOut: 'Thu nhỏ',
  resetView: 'Đặt lại view',
  docs: 'Tài liệu',

  // Node picker
  nodePickerTitle: 'Chọn node',
  nodePickerSearch: 'Tìm node...',
  nodePickerHint: '↑↓ Di chuyển · Enter Chọn · Esc Đóng',
  catInput: 'Input',
  catLlm: 'LLM',
  catGenerate: 'Generate',
  catEdit: 'Dựng video',
  catOutput: 'Output',
  catAnnotation: 'Annotation',

  // Nodes
  nodeAsset: 'Asset',
  nodeAssetDesc: 'Asset có sẵn trên Google Flow (hoặc file local) kèm label để dùng trong prompt',
  nodeText: 'Text',
  nodeTextDesc: 'Đã gộp vào Prompt',
  nodePrompt: 'Prompt',
  nodePromptDesc:
    'Nối prompt phía trước; giữ [Label] và mô tả; asset gửi Flow bằng media id; nhận Generate Video làm cảnh trước',
  flowPromptOrphanUrl:
    'Prompt chứa link Flow không gắn asset. Nối asset vào node để gửi bằng media id.',
  veoTooManyImageRefs: 'Veo chỉ nhận 1 ảnh start frame; bỏ bớt ảnh hoặc chọn Omni Flash',
  omniTooManyRefs: (max: number, n: number) =>
    `Chỉ nhận tối đa ${max} ảnh tham chiếu khi nối cảnh / Omni (đang có ${n}). Bỏ bớt ảnh rồi thử lại.`,
  refKindUnsupported: (label: string, kind: string) =>
    `[${label}] là ${kind}, model này chưa nhận làm tham chiếu`,
  flowMediaIdNotInPayload: (labels: string) =>
    `Media id không vào được payload RPC (${labels}). Kiểm tra model / số lượng ảnh tham chiếu.`,
  videoNeedsStartFrame:
    'Tạo video không tạo ảnh trung gian. Dùng Omni Flash (prompt thuần hoặc ảnh tham chiếu), hoặc nối đúng 1 ảnh start frame / cảnh trước cho Veo i2v.',
  continueStartFrameLabel: 'frame cuối cảnh trước',
  geminiInsertedFlowUrl: 'Gemini đã chèn link Flow vào prompt. Giữ [Label] và mô tả chữ, không dùng URL.',
  geminiDroppedLabels: (labels: string) =>
    `Gemini đã làm mất nhãn trong prompt: ${labels}. Giữ nguyên mọi [Label].`,
  defaultImageRefLabel: 'Ảnh',
  /** `[Label]` anchoring the previous scene's last frame in the Omni MZZa6b prompt. */
  continueFrameRefLabel: 'Cảnh trước',
  omniContinuePromptLead: (label: string) =>
    `Nối tiếp liền mạch từ khung hình cuối [${label}].\n\n`,
  extractLastFrameProgress: 'Lấy frame cuối của cảnh trước…',
  continueNoVideoFile: 'Cảnh trước chưa có file video để nối tiếp',
  continueFrameCacheMissing:
    'Không tìm thấy frame cuối đã lưu của cảnh trước. Nối lại Generate Video trước vào Prompt và chạy, hoặc bỏ frame đã lưu để tạo cảnh mới.',
  continueFrameCachedTitle: 'Frame cuối cảnh trước (đã lưu)',
  continueFrameCachedHint: 'Đã lưu - dùng khi không còn nối Generate Video trước',
  continueFrameClear: 'Bỏ frame đã lưu',
  incomingOriginCache: 'đã lưu',
  generateReusedPreviousClip: 'Không có prompt - dùng video đã tạo trước đó cho node phía sau',
  generateOnlyThisNode: 'Chỉ node này',
  generateOnlyThisNodeHint:
    'Chỉ chạy node này: node Generate phía trước dùng lại kết quả đã có, node Prompt dùng lại prompt đã phân tích (không gọi lại Gemini)',
  copyPrompt: 'Copy prompt',
  copyPromptDone: 'Đã copy',
  copyPromptHint: 'Copy prompt để dán vào Google Flow và tự bấm tạo',
  generateReusedForOnly: 'Dùng lại kết quả đã có (chỉ tạo node được chọn)',
  generateOnlyMissingUpstream: (name: string) =>
    `${name} chưa có kết quả để dùng lại. Chạy node đó trước, hoặc bấm Generate để tạo lại cả phía trước.`,
  omniReferenceDenied: (model: string) =>
    `MODEL_ACCESS_DENIED: tài khoản Flow này không dùng được Omni tham chiếu (${model}). Bỏ ảnh tham chiếu (Omni text-only) hoặc chọn model Veo.`,
  omniReferenceSubmitFailed: (model: string, detail: string) =>
    `Omni Flash tham chiếu bị từ chối (${model}): ${detail}`,
  veoReferenceDenied: (model: string) =>
    `MODEL_ACCESS_DENIED: tài khoản Flow này không dùng được Veo tham chiếu (${model}).`,
  veoReferenceSubmitFailed: (model: string, detail: string) =>
    `Veo tham chiếu (nối cảnh) bị từ chối (${model}): ${detail}`,
  veoContinueNoModel: (models: string) =>
    `Không model nối cảnh nào chạy được (${models}). ` +
    `Chọn Omni Flash để nối cảnh bằng ảnh tham chiếu, hoặc chạy Veo với đúng 1 ảnh start frame (không nối cảnh).`,
  veoContinueFallbackOmni:
    'Veo tham chiếu không dùng được - nối cảnh bằng Omni Flash (abra_r2v)…',
  /** `[5]` NOT_FOUND: Flow không phục vụ nhánh Veo r2v cho tài khoản này. */
  veoReferenceNotServed: (model: string) =>
    `Flow trả NOT_FOUND cho model nối cảnh ${model} - tài khoản không có nhánh Veo tham chiếu.`,
  flowUnusualActivity:
    'Google Flow tạm chặn vì nghi hoạt động bất thường (PUBLIC_ERROR_UNUSUAL_ACTIVITY). ' +
    'Dừng tạo khoảng 10-30 phút, mở tab Flow và tự tạo thử 1 ảnh bằng tay, rồi mới chạy lại.',
  /** Map Flow workflow failure codes (jwpduf) to actionable Vietnamese. */
  flowRenderFailureMessage: (code: string | null, reasons: string[]): string => {
    if (code === 'PUBLIC_ERROR_PROMINENT_PEOPLE_FILTER_FAILED') {
      return (
        'Google Flow từ chối vì ảnh tham chiếu hoặc mô tả bị lọc người nổi tiếng. ' +
        'Dùng ảnh stock/generic, tránh mô tả giống người thật có thể nhận diện; thử ảnh khác hoặc Omni text-only.'
      );
    }
    const detail = code ?? (reasons.length ? reasons.join(', ') : null) ?? 'không rõ';
    return `Flow từ chối render video: ${detail}`;
  },
  /** Veo i2v operation complained (often "Media not found" on a bad start frame). */
  flowVideoOpFailed: (detail: string) =>
    `Flow không tạo được video (${detail}). ` +
    `Thử ảnh start frame khác, hoặc nối cảnh bằng frame cuối (Veo/Omni qua ảnh tham chiếu).`,
  omniTextDenied: (model: string) =>
    `MODEL_ACCESS_DENIED: tài khoản Flow này không dùng được Omni Flash (${model}). Thử chọn model Veo.`,
  omniTextSubmitFailed: (model: string, detail: string) =>
    `Omni Flash bị từ chối (${model}): ${detail}`,
  omniUnknownLabelWarn: (labels: string) =>
    `Nhãn trong prompt không có asset nối vào: ${labels} (giữ chữ, không neo ảnh)`,
  nodeGenerateImage: 'Generate Image',
  nodeGenerateImageDesc: 'Tạo ảnh (tỉ lệ, số lượng, độ phân giải, model)',
  nodeGenerateVideo: 'Generate Video',
  nodeGenerateVideoDesc: 'Tạo video (tỉ lệ, độ dài, độ phân giải, model)',
  nodeMergeVideo: 'Ghép video',
  nodeMergeVideoDesc: 'Nối nhiều video, lồng audio và dán logo overlay',
  nodeAutoDownload: 'Auto Download',
  nodeAutoDownloadDesc: 'Tự tải kết quả của node trước',
  nodeNote: 'Note',
  nodeNoteDesc: 'Ghi chú trên canvas, không thực thi',
  // Ghép video
  mergeNoClips: 'Chưa nối video nào vào node Ghép video',
  mergeClipNoFile: (name: string) =>
    `Clip "${name}" chỉ có media id trên Google Flow, chưa có file để ghép — chạy lại node tạo video hoặc dùng asset file cục bộ`,
  mergeAudioNoFile: (name: string) =>
    `Audio "${name}" chưa có file cục bộ để ghép — chọn file audio từ máy`,
  mergeLogoNoFile: (name: string) =>
    `Logo "${name}" chưa có file cục bộ để ghép — chọn ảnh từ máy`,
  mergeStarting: (n: number) => `Ghép ${n} clip…`,
  mergeOutputName: 'Video đã ghép',
  mergeOrderTitle: 'Thứ tự ghép',
  mergeOrderEmpty: 'Nối các node video vào cổng 🎥 để ghép',
  mergeOrderCount: (n: number, total: string) => `${n} clip · ${total}`,
  mergeMoveUp: 'Lên trước',
  mergeMoveDown: 'Xuống sau',
  mergeClipNoPreview: 'Chưa chạy',
  mergeDurationUnknown: '—',
  mergeAudioTitle: 'Audio nền',
  mergeAudioEmpty: 'Nối 1 asset audio vào cổng 🔊 (thay toàn bộ tiếng gốc)',
  mergeAudioStart: 'Bắt đầu từ giây',
  mergeAudioStartHint: 'Cắt tới khi hết video; audio ngắn hơn thì phần cuối im lặng',
  mergeAudioRange: (from: string, to: string) => `Dùng đoạn ${from} → ${to}`,
  mergeAudioTooShort: 'Audio không đủ dài cho đoạn này — phần cuối video sẽ im lặng',
  mergeAudioStartTooLate: 'Mốc bắt đầu vượt quá độ dài file audio',
  mergeLogoTitle: 'Logo overlay',
  mergeLogoEmpty: 'Nối 1 asset ảnh vào cổng 🖼 để dán logo',
  mergeLogoDragHint: 'Kéo để đổi vị trí, kéo góc dưới-phải để đổi kích thước',
  mergeLogoSize: 'Rộng',
  mergeLogoOpacity: 'Độ mờ',
  mergeOutputTitle: 'Xuất',
  mergeFps: 'FPS',
  mergeBitrate: 'Bitrate (Mbps)',
  mergeFrameHint: 'Khung hình lấy theo clip đầu tiên; clip khác tỉ lệ sẽ có viền đen',
  mergeRun: 'Ghép video',
  mergeRunning: 'Đang ghép…',
  mergeExport: 'Tải video',
  mergeExportName: 'ghep-video',
  mergeResultTitle: 'Kết quả',
  mergeResultEmpty: 'Chưa ghép lần nào',
  mergeResultEmptyHint: 'Bấm Ghép video để tạo file mp4',
  mergeNotReady: 'Nối ít nhất 1 video vào cổng 🎥',

  assetLabel: 'Label',
  assetLocal: '· local',
  assetLocalAudio: '· local',
  missingFile: 'Thiếu file',
  pickFileAgain: 'Chọn lại',
  dropOrPick: 'Kéo thả hoặc chọn file',
  dropOrPickImage: 'Kéo thả hoặc chọn ảnh',
  dropOrPickVideo: 'Kéo thả hoặc chọn video',
  dropOrPickAudio: 'Kéo thả hoặc chọn audio',
  pickFromFlow: 'Từ Google Flow',
  pickFlowAssetHint: 'Chọn asset có sẵn trên Google Flow',
  pickFromLocal: 'Chọn file',
  flowPickerTitle: 'Chọn asset từ Google Flow',
  flowPickerHint:
    'Mở project trên tab Google Flow (flow.google.com). Danh sách tải theo trang — bấm số để xem thêm.',
  flowPickerTabFavorites: 'Yêu thích',
  flowPickerTabAll: 'Tất cả',
  flowPickerEmptyFavorites:
    'Chưa có asset yêu thích. Gắn sao trên Google Flow rồi bấm Làm mới, hoặc xem tab Tất cả.',
  flowPickerEmpty: 'Không thấy media nào. Hãy mở project có ảnh/video trên Flow rồi thử lại.',
  flowPickerLoading: 'Đang quét Google Flow…',
  flowPickerFetching: 'Đang tải asset…',
  flowPickerRefresh: 'Làm mới',
  flowPickerSelect: 'Dùng asset này',
  flowPickerNoMediaId: 'không có media id',
  flowPickerNoPreview: 'Không xem trước được',
  flowPickerSigning: 'Đang tải preview…',
  flowPickerPage: 'Trang',
  flowPickerPageOf: (current: number, total: number) => `Trang ${current}/${total}`,
  flowPickerPageCount: (n: number) => `${n} asset`,
  flowPickerLoadingPage: 'Đang tải trang…',
  flowPickerKindPending: '…',
  kindImage: 'Ảnh',
  kindVideo: 'Video',
  flowPickerPrev: 'Trước',
  flowPickerNext: 'Sau',
  flowPickerAuth: 'Chưa đăng nhập Google Flow. Đăng nhập trên tab Flow rồi thử lại.',
  flowPickerLogin: 'Đăng nhập Google Flow',
  flowPickerLoginHint: 'Đã mở tab Flow — đăng nhập xong quay lại bấm Làm mới.',
  flowPickerOpeningLogin: 'Đang mở Google Flow…',
  flowPickerConnError:
    'Không kết nối được tab Google Flow. Hãy mở https://flow.google.com , reload trang, rồi bấm Làm mới.',
  replaceAsset: 'Đổi asset',
  preview: 'Preview',
  aspectRatio: 'Tỉ lệ khung hình',
  outputCount: 'Số lượng tạo ra',
  resolution: 'Độ phân giải',
  imageResolution: 'Độ phân giải ảnh',
  durationSec: 'Độ dài video (giây)',
  model: 'Model',
  inspectorTitle: 'Inspector',
  providerFlow: 'Google Flow',
  providerGemini: 'Gemini',

  // Prompt presets (fashion + reuse)
  presetEnhance: 'Cải thiện prompt',
  presetAnalyzeImage: 'Phân tích ảnh',
  presetScript: 'Viết kịch bản',
  presetSummarize: 'Tóm tắt',
  presetTranslate: 'Dịch',
  presetBrainstorm: 'Động não',
  presetCustom: 'Tuỳ chỉnh',
  presetFashionScene: 'Phân tích scene thời trang',
  presetFashionModel: 'Phân tích người mẫu',
  presetFashionOutfit: 'Phân tích outfit',
  presetFashionColor: 'Phối màu thời trang',
  presetFashionCompose: 'Ghép prompt thời trang',
  reusePrompt: 'Dùng lại prompt cũ',
  forwardRefs: 'Chuyển tiếp ảnh xuống node sau',
  promptReused: 'Dùng lại',
  promptFresh: 'Mới phân tích',
  promptOutputNotAnalyzed: 'Chưa phân tích - bấm Chạy node để gọi Gemini',
  promptOutputPreviewHint: 'Instruction + prompt phía trước; [Label] + mô tả · mediaId {uuid}',
  promptFetchFlowImage: (i: number, n: number) => `Đang tải ảnh từ Flow (${i}/${n})…`,
  promptFlowImageFetchFailed: (label: string, reason: string) =>
    `Không tải được ảnh ${label} từ Google Flow để gửi Gemini: ${reason}`,
  promptSendingGemini: 'Gửi prompt tới Gemini…',
  flowMediaSignFailed: 'Flow không trả về link tải cho media này (media đã bị xoá hoặc không thuộc project đang mở)',
  geminiTypingPrompt: 'Nhập prompt…',
  geminiUploadingImages: (i: number, n: number) => `Đang tải ảnh lên Gemini (${i}/${n})…`,
  geminiAttachFailed: 'Gemini không nhận ảnh đính kèm - tải lại tab Gemini rồi chạy lại',
  geminiSwitchingAccount: 'Chuyển Gemini sang tài khoản của Flow…',
  geminiAccountMismatch: (gemini: string, flow: string) =>
    `Gemini đang dùng tài khoản ${gemini}, Flow dùng ${flow} - đăng nhập ${flow} trên gemini.google.com rồi chạy lại`,
  geminiSent: 'Đã gửi, chờ Gemini…',
  geminiAnswering: (chars: number, sec: number) => `Gemini đang trả lời… ${chars} ký tự · ${sec}s`,
  geminiTimeout: (sec: number, stopLabel: string, chars: number) =>
    `Gemini không trả lời xong sau ${sec}s (nút dừng: ${stopLabel || 'không thấy'}, đã nhận ${chars} ký tự) - kiểm tra tab Gemini rồi chạy lại`,
  geminiNoReply: (sec: number) =>
    `Gemini chưa nhận prompt sau ${sec}s (không có câu trả lời mới) - mở tab Gemini xem prompt đã được gửi chưa rồi chạy lại`,
  geminiNoResponse: 'Không lấy được phản hồi từ Gemini',
  geminiDone: 'Xong',
  promptOutputChars: (n: number) => `Output · ${n} ký tự`,
  fashionJsonInvalid: 'Kết quả phân tích thời trang không phải JSON hợp lệ',
  fashionJsonMissingType: (type: string) => `Thiếu khối JSON loại "${type}" để ghép prompt`,
  fashionComposeEmpty: 'Chưa có đủ khối phân tích để ghép prompt thời trang',
  promptJsonInvalid: 'Output không phải JSON hợp lệ',
  flowFetchingImage: 'Tải ảnh…',
  flowFetchingImage2k: 'Tải ảnh 2K…',
  flowImage2kEmpty: 'SPrCad không trả JPEG 2K',
  workflowOutputStats: (images: number, videos: number) => `${images} ảnh · ${videos} video`,
  workflowOutputEmpty: '0 ảnh',

  // Upload Flow một lần + panel phân tích
  assetUploading: 'Đang upload lên Flow…',
  assetUploaded: 'Đã có trên Flow',
  assetUploadError: (detail: string | null) =>
    `Upload lên Flow lỗi: ${detail?.trim() || 'không rõ nguyên nhân'}`,
  assetUploadRetry: 'Upload lại',
  flowUploadNoTab: 'Chưa mở tab Google Flow - mở một project Flow rồi bấm Upload lại',
  flowUploadNodeNotLocal: 'Node không có ảnh local để upload lên Flow',
  flowUploadedMediaGone: (detail: string) =>
    `Flow không tìm thấy ảnh đã upload, kể cả sau khi upload lại từ file gốc: ${detail}`,
  promptAnalyze: 'Phân tích',
  promptReanalyze: 'Phân tích lại',
  promptSkill: 'Skill',
  promptSkillReset: 'Khôi phục mặc định',
  promptResult: 'Kết quả',
  promptEdited: 'Đã sửa tay',
  promptResultEmpty: 'Chưa có kết quả phân tích',

  // Status
  statusQueued: 'Đang chờ',
  statusRunning: 'Đang chạy',
  statusUploading: 'Đang tải lên',
  statusGenerating: 'Đang tạo',
  statusSuccess: 'Xong',
  statusError: 'Lỗi',
  statusSkipped: 'Bỏ qua',
  statusCancelled: 'Đã huỷ',
  authRequired: 'Chưa đăng nhập provider',
  quotaExceeded: 'Hết hạn mức',
  contentPolicy: 'Vi phạm chính sách nội dung',
  timeout: 'Hết thời gian chờ',
  selectorNotFound: 'Không tìm thấy phần tử UI',
  uploadFailed: 'Tải file thất bại',
  tabLost: 'Tab provider bị đóng',
  unknownError: 'Lỗi không xác định',

  // Export / Import
  exportTitle: 'Export workflow',
  exportFormat: 'Định dạng',
  exportFormatZip: '.xflow.zip (mặc định)',
  exportFormatJson: '.xflow.json',
  exportIncludeAssets: 'Kèm file media',
  exportIncludeOutputs: 'Kèm kết quả chạy gần nhất',
  exportSummary: (w: number, n: number, a: number, size: string) =>
    `${w} workflow · ${n} nodes · ${a} asset · ~${size}`,
  exportWorkspace: 'Export workspace',
  exportWorkspaceTitle: 'Export workspace',
  importTitle: 'Import workflow',
  importPreview: 'Xem trước import',
  importTargetWorkspace: 'Workspace đích',
  importCreateWorkspace: 'Tạo workspace mới từ file',
  importDupCopy: 'Tạo bản sao',
  importDupOverwrite: 'Ghi đè',
  importDupSkip: 'Bỏ qua',
  importCommit: 'Nhập',
  importDropZone: 'Thả file .xflow.zip / .xflow.json vào đây',
  importDropCanvas: 'Mở thành workflow mới hoặc chèn node vào workflow hiện tại?',
  importOpenNew: 'Mở thành workflow mới',
  importInsert: 'Chèn node vào workflow hiện tại',
  importTooNew: 'File được tạo từ phiên bản mới hơn, hãy cập nhật extension',
  importInvalid: 'File không hợp lệ',
  importSuccess: (n: number) => `Đã nhập ${n} workflow`,
  importWorkspace: 'Import workspace',
  importAssetMissing: (nodeLabel: string) => `Thiếu media cho node ${nodeLabel}`,
  importAssetMissingJson: 'Thiếu file media (json)',
  importFlowAssetMissing: (nodeLabel: string) =>
    `Asset Flow "${nodeLabel}" chỉ dùng được với tài khoản Flow gốc - chọn lại asset hoặc dùng file local`,
  backup: 'Backup',
  restore: 'Restore',
  backupDone: 'Đã tạo bản backup',
  restoreDone: 'Đã khôi phục dữ liệu',
  restoreConfirm: 'Restore sẽ ghi đè dữ liệu hiện tại. Tiếp tục?',

  // Settings
  settingsTitle: 'Cài đặt',
  settingsDownloadFolder: 'Thư mục tải mặc định',
  settingsImportMaxZip: 'Giới hạn zip import (MB)',
  settingsImportMaxJson: 'Giới hạn json import (MB)',
  settingsDefaultConcurrency: 'Concurrency mặc định',
  settingsDefaultGeminiModel: 'Model Gemini mặc định',
  settingsRemoteConfig: 'Remote selector config URL',
  settingsVersion: 'Phiên bản',
  settingsCheckUpdate: 'Kiểm tra cập nhật',
  settingsStorageEstimate: 'Dung lượng đã dùng',
  settingsCleanup: 'Dọn asset/output mồ côi',
  settingsProviderStatus: 'Tình trạng provider',
  settingsDiagnose: 'Chẩn đoán selector',
  providerOk: 'Đã đăng nhập',
  providerUnauth: 'Chưa đăng nhập',
  providerError: 'Driver lỗi',

  // Queue footer
  queueRunning: (n: number) => `Đang chạy ${n}`,
  queueWaiting: (n: number) => `Chờ ${n}`,
  queueIdle: 'Hàng đợi trống',

  // Runner (cửa sổ "Chạy")
  runnerTitle: 'Chạy',
  openRunner: 'Tải lên',
  selectedCount: (n: number) => `Đã chọn ${n}`,
  runnerRunAll: 'Chạy toàn bộ',
  runnerStop: 'Dừng',
  runnerOpenEditor: 'Mở editor node',
  runnerRegenerate: 'Tạo lại',
  runnerExportVideo: 'Tải video',
  runnerEmptyAssets: 'Workflow này không có ô upload asset',
  runnerEmptyGenerates: 'Workflow này không có node tạo ảnh/video',
  runnerWaitingClips: 'Đang chờ đủ clip',
  runnerDeleted: 'Workflow đã bị xoá',
  runnerLocked: 'Workflow đang khoá - chỉ xem và chạy',
  runnerNotFound: 'Không tìm thấy workflow',
  runnerGraphError: 'Workflow có vòng (cycle), không thể chạy',
  runnerWrongMediaKind: (kind: string) =>
    `Ô này chỉ nhận ${kind === 'image' ? 'ảnh' : kind === 'video' ? 'video' : 'audio'}`,
  runnerFlowAudioUnsupported: 'Ô audio không chọn được asset từ Google Flow',
  runnerMissingFile: 'Thiếu file - chọn lại',
  runnerUserError: 'Không lưu được thay đổi',
  runnerLoading: 'Đang tải workflow…',
  runnerAssetsColumn: 'Asset',
  runnerScenesColumn: 'Cảnh',
  runnerFinalColumn: 'Video cuối',
  runnerMoveUp: 'Lên trước',
  runnerMoveDown: 'Xuống sau',
  runnerGeminiOutput: 'Kết quả Gemini',
  runnerNodeId: 'ID',
  runnerPromptLabel: 'Prompt',
  runnerInstructionLabel: 'Instruction',
  runnerPresetLabel: 'Preset',
  runnerAssetCount: (n: number) => `${n} ô`,
  runnerSceneCount: (n: number) => `${n} cảnh`,
  runnerHasAsset: 'Đã chọn',
  runnerNoAsset: 'Chưa có asset',
  runnerRunningHint: 'Đang chạy workflow…',
  runnerMergeProgress: 'Đang ghép video',
  runnerNoMerge: 'Workflow này không có node ghép video',
  runnerPlay: 'Phát',
  runnerPause: 'Tạm dừng',
  kindAudio: 'Audio',

  // Common
  confirm: 'Xác nhận',
  ok: 'OK',
  yes: 'Có',
  no: 'Không',
  loading: 'Đang tải…',
  error: 'Lỗi',
  success: 'Thành công',
  justNow: 'vừa xong',
} as const;

export type Strings = typeof strings;

const PROMPT_PRESET_LABELS: Record<string, string> = {
  enhance: strings.presetEnhance,
  analyzeImage: strings.presetAnalyzeImage,
  script: strings.presetScript,
  summarize: strings.presetSummarize,
  translate: strings.presetTranslate,
  brainstorm: strings.presetBrainstorm,
  custom: strings.presetCustom,
  fashionScene: strings.presetFashionScene,
  fashionModel: strings.presetFashionModel,
  fashionOutfit: strings.presetFashionOutfit,
  fashionColor: strings.presetFashionColor,
  fashionCompose: strings.presetFashionCompose,
};

/** Nhãn tiếng Việt cho preset Prompt; value vẫn là enum key. */
export function promptPresetLabel(preset: string): string {
  return PROMPT_PRESET_LABELS[preset] ?? preset;
}
