import type { Template } from '@/shared/schema';
import { SCHEMA_VERSION } from '@/shared/schema';

/** Built-in: Character + Outfit → Prompt → Omni Flash (media id slots, no CDN links). */
export function getSeedTemplates(): Template[] {
  const now = Date.now();
  return [
    {
      id: 'tpl-character-outfit-omni',
      name: 'Nhân vật + trang phục → Omni Flash',
      description:
        'Asset Character + Outfit (có sẵn trên Flow) → Prompt giữ [Label] và mô tả → Generate Video Omni Flash neo ảnh trong structured prompt (MZZa6b).',
      category: 'character',
      tags: ['flow', 'omni', 'character'],
      builtIn: true,
      createdAt: now,
      updatedAt: now,
      workflow: {
        id: 'tpl-character-outfit-omni',
        schemaVersion: SCHEMA_VERSION,
        name: 'Nhân vật + trang phục → Omni Flash',
        locked: false,
        nodes: [
          {
            id: 'note-1',
            type: 'note',
            position: { x: 40, y: 40 },
            data: {
              content:
                'Chọn 2 ảnh có sẵn trên Google Flow cho Character và Outfit. Đặt [Label] đúng chỗ neo ảnh trong câu. Omni Flash gửi MZZa6b (abra_r2v_*) với media id — không dán link Flow.',
              color: '#1e3a5f',
              fontSize: 13,
            },
          },
          {
            id: 'asset-character',
            type: 'asset',
            slug: 'character',
            label: 'Character',
            position: { x: 40, y: 160 },
            data: {
              kind: 'image',
              assetLabel: 'Character',
              slug: 'character',
              source: 'flow',
            },
          },
          {
            id: 'asset-outfit',
            type: 'asset',
            slug: 'outfit',
            label: 'Outfit',
            position: { x: 40, y: 380 },
            data: {
              kind: 'image',
              assetLabel: 'Outfit',
              slug: 'outfit',
              source: 'flow',
            },
          },
          {
            id: 'prompt-1',
            type: 'prompt',
            label: 'Prompt',
            position: { x: 400, y: 220 },
            data: {
              provider: 'gemini',
              model: '',
              preset: 'custom',
              instruction:
                'Video dọc 9:16 dài 4 giây, phong cách quay thực tế.\n' +
                '[Character] mặc [Outfit] đi bộ về phía máy quay trên con phố đầy nắng, khẽ mỉm cười.\n' +
                'Giữ nguyên gương mặt, kiểu tóc và từng chi tiết trang phục như ảnh tham chiếu; không thêm, bớt hay đổi màu quần áo và phụ kiện.\n' +
                'Góc máy: toàn thân đến trung cảnh, máy lùi chậm.\n' +
                'Ánh sáng: nắng tự nhiên buổi sáng, mềm.\n\n' +
                '[Character]: Cô gái Đông Á 20-25 tuổi, mặt trái xoan, da sáng, tóc đen thẳng ngang vai.\n\n' +
                '[Outfit]: Áo blazer linen màu kem dáng rộng, áo ba lỗ trắng, quần jeans ống rộng, sneaker trắng.',
              outputFormat: 'plain',
              newChat: true,
            },
          },
          {
            id: 'gen-video-1',
            type: 'generateVideo',
            label: 'Generate Video',
            position: { x: 1000, y: 220 },
            data: {
              model: 'Omni Flash',
              aspectRatio: '9:16',
              count: 1,
              resolution: 720,
              durationSec: 4,
              timeoutSec: 600,
            },
          },
          {
            id: 'download-1',
            type: 'autoDownload',
            label: 'Auto Download',
            position: { x: 1600, y: 280 },
            data: {
              folderTemplate: 'MyXFlows/{{workflow}}/{{date}}',
              filenameTemplate: '{{slug}}_{{index}}',
              conflict: 'uniquify',
              onlyWhenAllDone: false,
            },
          },
        ],
        edges: [
          {
            id: 'e1',
            source: 'asset-character',
            sourceHandle: 'out:image',
            target: 'prompt-1',
            targetHandle: 'in:image',
            type: 'image',
          },
          {
            id: 'e2',
            source: 'asset-outfit',
            sourceHandle: 'out:image',
            target: 'prompt-1',
            targetHandle: 'in:image',
            type: 'image',
          },
          {
            id: 'e3',
            source: 'prompt-1',
            sourceHandle: 'out:text',
            target: 'gen-video-1',
            targetHandle: 'in:text',
            type: 'text',
          },
          {
            id: 'e4',
            source: 'gen-video-1',
            sourceHandle: 'out:video',
            target: 'download-1',
            targetHandle: 'in:any',
            type: 'video',
          },
        ],
        viewport: { x: 0, y: 0, zoom: 0.85 },
        settings: { concurrency: 1, retry: 0, stopOnError: true },
        createdAt: now,
        updatedAt: now,
      },
    },
    {
      id: 'tpl-fashion-image',
      name: 'Tạo hình thời trang',
      description:
        'Ảnh mẫu + người mẫu + outfit → phân tích Gemini (scene/model/outfit/màu) → ghép prompt → Generate Image 2K 9:16 → Auto Download. Chỉ đổi outfit rồi chạy lại.',
      category: 'fashion',
      tags: ['flow', 'fashion', 'image', '2k'],
      builtIn: true,
      createdAt: now,
      updatedAt: now,
      workflow: {
        id: 'tpl-fashion-image',
        schemaVersion: SCHEMA_VERSION,
        name: 'Tạo hình thời trang',
        locked: false,
        nodes: [
          {
            id: 'note-fashion',
            type: 'note',
            position: { x: 40, y: 20 },
            data: {
              content:
                'Chọn 3 ảnh local: Ảnh mẫu (scene), Người mẫu, Outfit. ' +
                'Preset scene tắt chuyển tiếp ảnh nên ảnh mẫu không sang Flow. ' +
                'Phối màu: đổi instruction sang "Phong cách: trẻ đẹp" hoặc "Phong cách: năng động" nếu muốn. ' +
                'Lần chạy sau chỉ đổi Outfit - scene/model dùng lại prompt khi bật "Dùng lại".',
              color: '#3b2f2f',
              fontSize: 13,
            },
          },
          {
            id: 'asset-scene',
            type: 'asset',
            slug: 'scene',
            label: 'Ảnh mẫu',
            position: { x: 40, y: 180 },
            data: {
              kind: 'image',
              assetLabel: 'Background',
              slug: 'scene',
              source: 'local',
            },
          },
          {
            id: 'asset-model',
            type: 'asset',
            slug: 'model',
            label: 'Người mẫu',
            position: { x: 40, y: 380 },
            data: {
              kind: 'image',
              assetLabel: 'Character',
              slug: 'model',
              source: 'local',
            },
          },
          {
            id: 'asset-outfit',
            type: 'asset',
            slug: 'outfit',
            label: 'Outfit',
            position: { x: 40, y: 580 },
            data: {
              kind: 'image',
              assetLabel: 'Outfit',
              slug: 'outfit',
              source: 'local',
            },
          },
          {
            id: 'prompt-scene',
            type: 'prompt',
            label: 'Phân tích scene',
            position: { x: 360, y: 180 },
            data: {
              provider: 'gemini',
              model: '',
              preset: 'fashionScene',
              instruction: '',
              outputFormat: 'json',
              newChat: true,
              reusePrompt: true,
              forwardRefs: true,
            },
          },
          {
            id: 'prompt-model',
            type: 'prompt',
            label: 'Phân tích người mẫu',
            position: { x: 360, y: 380 },
            data: {
              provider: 'gemini',
              model: '',
              preset: 'fashionModel',
              instruction: '',
              outputFormat: 'json',
              newChat: true,
              reusePrompt: true,
              forwardRefs: true,
            },
          },
          {
            id: 'prompt-outfit',
            type: 'prompt',
            label: 'Phân tích outfit',
            position: { x: 360, y: 580 },
            data: {
              provider: 'gemini',
              model: '',
              preset: 'fashionOutfit',
              instruction: '',
              outputFormat: 'json',
              newChat: true,
              reusePrompt: true,
              forwardRefs: true,
            },
          },
          {
            id: 'prompt-color',
            type: 'prompt',
            label: 'Phối màu',
            position: { x: 700, y: 280 },
            data: {
              provider: 'gemini',
              model: '',
              preset: 'fashionColor',
              instruction:
                'Phong cách: sang trọng\n' +
                '(Các lựa chọn: sang trọng / trẻ đẹp / năng động - sửa dòng trên để đổi palette.)',
              outputFormat: 'json',
              newChat: true,
              reusePrompt: true,
              forwardRefs: true,
            },
          },
          {
            id: 'prompt-compose',
            type: 'prompt',
            label: 'Ghép prompt',
            position: { x: 1040, y: 360 },
            data: {
              provider: 'gemini',
              model: '',
              preset: 'fashionCompose',
              instruction: '',
              outputFormat: 'plain',
              newChat: true,
              reusePrompt: false,
              forwardRefs: true,
            },
          },
          {
            id: 'gen-image-1',
            type: 'generateImage',
            label: 'Generate Image',
            position: { x: 1400, y: 360 },
            data: {
              model: 'Nano Banana 2',
              aspectRatio: '9:16',
              count: 1,
              resolution: '2K',
              timeoutSec: 600,
            },
          },
          {
            id: 'download-fashion',
            type: 'autoDownload',
            label: 'Auto Download',
            position: { x: 1760, y: 400 },
            data: {
              folderTemplate: 'MyXFlows/{{workflow}}/{{date}}',
              filenameTemplate: '{{slug}}_{{index}}',
              conflict: 'uniquify',
              onlyWhenAllDone: false,
            },
          },
        ],
        edges: [
          {
            id: 'fe-scene-asset',
            source: 'asset-scene',
            sourceHandle: 'out:image',
            target: 'prompt-scene',
            targetHandle: 'in:image',
            type: 'image',
          },
          {
            id: 'fe-model-asset',
            source: 'asset-model',
            sourceHandle: 'out:image',
            target: 'prompt-model',
            targetHandle: 'in:image',
            type: 'image',
          },
          {
            id: 'fe-outfit-asset',
            source: 'asset-outfit',
            sourceHandle: 'out:image',
            target: 'prompt-outfit',
            targetHandle: 'in:image',
            type: 'image',
          },
          {
            id: 'fe-scene-compose',
            source: 'prompt-scene',
            sourceHandle: 'out:text',
            target: 'prompt-compose',
            targetHandle: 'in:text',
            type: 'text',
          },
          {
            id: 'fe-model-compose',
            source: 'prompt-model',
            sourceHandle: 'out:text',
            target: 'prompt-compose',
            targetHandle: 'in:text',
            type: 'text',
          },
          {
            id: 'fe-outfit-compose',
            source: 'prompt-outfit',
            sourceHandle: 'out:text',
            target: 'prompt-compose',
            targetHandle: 'in:text',
            type: 'text',
          },
          {
            id: 'fe-color-compose',
            source: 'prompt-color',
            sourceHandle: 'out:text',
            target: 'prompt-compose',
            targetHandle: 'in:text',
            type: 'text',
          },
          {
            id: 'fe-compose-gen',
            source: 'prompt-compose',
            sourceHandle: 'out:text',
            target: 'gen-image-1',
            targetHandle: 'in:text',
            type: 'text',
          },
          {
            id: 'fe-gen-dl',
            source: 'gen-image-1',
            sourceHandle: 'out:image',
            target: 'download-fashion',
            targetHandle: 'in:any',
            type: 'image',
          },
        ],
        viewport: { x: 0, y: 0, zoom: 0.7 },
        settings: { concurrency: 1, retry: 0, stopOnError: true },
        createdAt: now,
        updatedAt: now,
      },
    },
  ];
}
